name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  AWS_REGION: "us-east-1"  
  
  contents: read
    
jobs:
  tf-fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
     
        - name: Checkout Repo
          uses: actions/checkout@v3

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.1.7
        

          
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TF_ACTION_WORKING_DIR: 'terraform'
            AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
        - name: terraform init
          run: |
            cd terraform
            ls
            terraform init
            echo "AWS Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
            echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
                     
        - name: terraform validate
          run: |
            cd terraform
            ls 
            terraform validate

        - name: terraform apply
          run: |
            cd terraform
            ls
            terraform apply -auto-approve

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TF_ACTION_WORKING_DIR: 'terraform'
            AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
        # - name: terraform destroy
        #   run: |
        #     cd terraform
        #     ls
        #     terraform destroy -auto-approve

        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #     TF_ACTION_WORKING_DIR: 'terraform'
        #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.0.0

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     TF_ACTION_WORKING_DIR: 'terraform'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: Set Lambda Function URL as Output
          id: lambda-url
          run:
            FUNCTION_URL=$(terraform output function_url)
            echo "::set-output name=lambda_url::$FUNCTION_URL"
           
        - name: Get Lambda Function URL
          run: echo "Lambda Function URL:${{ steps.lambda-url.outputs.lambda_url }}"
